from typing import Protocol, Iterable

from tinyshop.domain.cart_Item import Cart
from tinyshop.domain.order import Order
from tinyshop.domain.product import Product


class ProductRepository(Protocol):
    def add(self, product: Product) -> None: ...

    def get(self, product_id: int) -> Product: ...

    def list(self) -> Iterable[Product]: ...

    def remove(self, product_id: int) -> None: ...

class CartRepository(Protocol):
    def add(self,cart:Cart) -> None: ...
    def get(self, cart_id:int) -> Cart: ...
    def list(self) -> Iterable[Cart]: ...
    def remove(self,cart_id:int) -> None:...


class OrderRepository(Protocol):
    def add(self, order: Order) -> None: ...

    def get(self, order_id: int) -> Order: ...

    def list(self) -> Iterable[Order]: ...

    def remove(self, order_id: int) -> None: ...
